// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addressbook.proto

package co.za.ravi.spark.protobuf;

public final class AddressBooks {
  private AddressBooks() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PersonOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string name = 1;
    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // required int32 id = 2;
    /**
     * <code>required int32 id = 2;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 2;</code>
     */
    int getId();

    // required string email = 3;
    /**
     * <code>required string email = 3;</code>
     */
    boolean hasEmail();
    /**
     * <code>required string email = 3;</code>
     */
    java.lang.String getEmail();
    /**
     * <code>required string email = 3;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    // repeated .protobufexample.Person.Phone phone = 4;
    /**
     * <code>repeated .protobufexample.Person.Phone phone = 4;</code>
     */
    java.util.List<co.za.ravi.spark.protobuf.AddressBooks.Person.Phone> 
        getPhoneList();
    /**
     * <code>repeated .protobufexample.Person.Phone phone = 4;</code>
     */
    co.za.ravi.spark.protobuf.AddressBooks.Person.Phone getPhone(int index);
    /**
     * <code>repeated .protobufexample.Person.Phone phone = 4;</code>
     */
    int getPhoneCount();
    /**
     * <code>repeated .protobufexample.Person.Phone phone = 4;</code>
     */
    java.util.List<? extends co.za.ravi.spark.protobuf.AddressBooks.Person.PhoneOrBuilder> 
        getPhoneOrBuilderList();
    /**
     * <code>repeated .protobufexample.Person.Phone phone = 4;</code>
     */
    co.za.ravi.spark.protobuf.AddressBooks.Person.PhoneOrBuilder getPhoneOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code protobufexample.Person}
   */
  public static final class Person extends
      com.google.protobuf.GeneratedMessage
      implements PersonOrBuilder {
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Person(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Person defaultInstance;
    public static Person getDefaultInstance() {
      return defaultInstance;
    }

    public Person getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Person(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              id_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              email_ = input.readBytes();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                phone_ = new java.util.ArrayList<co.za.ravi.spark.protobuf.AddressBooks.Person.Phone>();
                mutable_bitField0_ |= 0x00000008;
              }
              phone_.add(input.readMessage(co.za.ravi.spark.protobuf.AddressBooks.Person.Phone.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          phone_ = java.util.Collections.unmodifiableList(phone_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return co.za.ravi.spark.protobuf.AddressBooks.internal_static_protobufexample_Person_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return co.za.ravi.spark.protobuf.AddressBooks.internal_static_protobufexample_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              co.za.ravi.spark.protobuf.AddressBooks.Person.class, co.za.ravi.spark.protobuf.AddressBooks.Person.Builder.class);
    }

    public static com.google.protobuf.Parser<Person> PARSER =
        new com.google.protobuf.AbstractParser<Person>() {
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Person(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code protobufexample.Person.PhoneType}
     */
    public enum PhoneType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>HOME = 0;</code>
       */
      HOME(0, 0),
      /**
       * <code>WORK = 1;</code>
       */
      WORK(1, 1),
      /**
       * <code>MOBILE = 2;</code>
       */
      MOBILE(2, 2),
      ;

      /**
       * <code>HOME = 0;</code>
       */
      public static final int HOME_VALUE = 0;
      /**
       * <code>WORK = 1;</code>
       */
      public static final int WORK_VALUE = 1;
      /**
       * <code>MOBILE = 2;</code>
       */
      public static final int MOBILE_VALUE = 2;


      public final int getNumber() { return value; }

      public static PhoneType valueOf(int value) {
        switch (value) {
          case 0: return HOME;
          case 1: return WORK;
          case 2: return MOBILE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<PhoneType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<PhoneType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<PhoneType>() {
              public PhoneType findValueByNumber(int number) {
                return PhoneType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return co.za.ravi.spark.protobuf.AddressBooks.Person.getDescriptor().getEnumTypes().get(0);
      }

      private static final PhoneType[] VALUES = values();

      public static PhoneType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private PhoneType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:protobufexample.Person.PhoneType)
    }

    public interface PhoneOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required string phoneNumber = 1;
      /**
       * <code>required string phoneNumber = 1;</code>
       */
      boolean hasPhoneNumber();
      /**
       * <code>required string phoneNumber = 1;</code>
       */
      java.lang.String getPhoneNumber();
      /**
       * <code>required string phoneNumber = 1;</code>
       */
      com.google.protobuf.ByteString
          getPhoneNumberBytes();

      // optional .protobufexample.Person.PhoneType type = 2 [default = MOBILE];
      /**
       * <code>optional .protobufexample.Person.PhoneType type = 2 [default = MOBILE];</code>
       */
      boolean hasType();
      /**
       * <code>optional .protobufexample.Person.PhoneType type = 2 [default = MOBILE];</code>
       */
      co.za.ravi.spark.protobuf.AddressBooks.Person.PhoneType getType();
    }
    /**
     * Protobuf type {@code protobufexample.Person.Phone}
     */
    public static final class Phone extends
        com.google.protobuf.GeneratedMessage
        implements PhoneOrBuilder {
      // Use Phone.newBuilder() to construct.
      private Phone(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Phone(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Phone defaultInstance;
      public static Phone getDefaultInstance() {
        return defaultInstance;
      }

      public Phone getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Phone(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                phoneNumber_ = input.readBytes();
                break;
              }
              case 16: {
                int rawValue = input.readEnum();
                co.za.ravi.spark.protobuf.AddressBooks.Person.PhoneType value = co.za.ravi.spark.protobuf.AddressBooks.Person.PhoneType.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(2, rawValue);
                } else {
                  bitField0_ |= 0x00000002;
                  type_ = value;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return co.za.ravi.spark.protobuf.AddressBooks.internal_static_protobufexample_Person_Phone_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return co.za.ravi.spark.protobuf.AddressBooks.internal_static_protobufexample_Person_Phone_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                co.za.ravi.spark.protobuf.AddressBooks.Person.Phone.class, co.za.ravi.spark.protobuf.AddressBooks.Person.Phone.Builder.class);
      }

      public static com.google.protobuf.Parser<Phone> PARSER =
          new com.google.protobuf.AbstractParser<Phone>() {
        public Phone parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Phone(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Phone> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required string phoneNumber = 1;
      public static final int PHONENUMBER_FIELD_NUMBER = 1;
      private java.lang.Object phoneNumber_;
      /**
       * <code>required string phoneNumber = 1;</code>
       */
      public boolean hasPhoneNumber() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string phoneNumber = 1;</code>
       */
      public java.lang.String getPhoneNumber() {
        java.lang.Object ref = phoneNumber_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            phoneNumber_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string phoneNumber = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPhoneNumberBytes() {
        java.lang.Object ref = phoneNumber_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          phoneNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // optional .protobufexample.Person.PhoneType type = 2 [default = MOBILE];
      public static final int TYPE_FIELD_NUMBER = 2;
      private co.za.ravi.spark.protobuf.AddressBooks.Person.PhoneType type_;
      /**
       * <code>optional .protobufexample.Person.PhoneType type = 2 [default = MOBILE];</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .protobufexample.Person.PhoneType type = 2 [default = MOBILE];</code>
       */
      public co.za.ravi.spark.protobuf.AddressBooks.Person.PhoneType getType() {
        return type_;
      }

      private void initFields() {
        phoneNumber_ = "";
        type_ = co.za.ravi.spark.protobuf.AddressBooks.Person.PhoneType.MOBILE;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasPhoneNumber()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getPhoneNumberBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeEnum(2, type_.getNumber());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getPhoneNumberBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(2, type_.getNumber());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static co.za.ravi.spark.protobuf.AddressBooks.Person.Phone parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static co.za.ravi.spark.protobuf.AddressBooks.Person.Phone parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static co.za.ravi.spark.protobuf.AddressBooks.Person.Phone parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static co.za.ravi.spark.protobuf.AddressBooks.Person.Phone parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static co.za.ravi.spark.protobuf.AddressBooks.Person.Phone parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static co.za.ravi.spark.protobuf.AddressBooks.Person.Phone parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static co.za.ravi.spark.protobuf.AddressBooks.Person.Phone parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static co.za.ravi.spark.protobuf.AddressBooks.Person.Phone parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static co.za.ravi.spark.protobuf.AddressBooks.Person.Phone parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static co.za.ravi.spark.protobuf.AddressBooks.Person.Phone parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(co.za.ravi.spark.protobuf.AddressBooks.Person.Phone prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code protobufexample.Person.Phone}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements co.za.ravi.spark.protobuf.AddressBooks.Person.PhoneOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return co.za.ravi.spark.protobuf.AddressBooks.internal_static_protobufexample_Person_Phone_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return co.za.ravi.spark.protobuf.AddressBooks.internal_static_protobufexample_Person_Phone_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  co.za.ravi.spark.protobuf.AddressBooks.Person.Phone.class, co.za.ravi.spark.protobuf.AddressBooks.Person.Phone.Builder.class);
        }

        // Construct using co.za.ravi.spark.protobuf.AddressBooks.Person.Phone.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          phoneNumber_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          type_ = co.za.ravi.spark.protobuf.AddressBooks.Person.PhoneType.MOBILE;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return co.za.ravi.spark.protobuf.AddressBooks.internal_static_protobufexample_Person_Phone_descriptor;
        }

        public co.za.ravi.spark.protobuf.AddressBooks.Person.Phone getDefaultInstanceForType() {
          return co.za.ravi.spark.protobuf.AddressBooks.Person.Phone.getDefaultInstance();
        }

        public co.za.ravi.spark.protobuf.AddressBooks.Person.Phone build() {
          co.za.ravi.spark.protobuf.AddressBooks.Person.Phone result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public co.za.ravi.spark.protobuf.AddressBooks.Person.Phone buildPartial() {
          co.za.ravi.spark.protobuf.AddressBooks.Person.Phone result = new co.za.ravi.spark.protobuf.AddressBooks.Person.Phone(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.phoneNumber_ = phoneNumber_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.type_ = type_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof co.za.ravi.spark.protobuf.AddressBooks.Person.Phone) {
            return mergeFrom((co.za.ravi.spark.protobuf.AddressBooks.Person.Phone)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(co.za.ravi.spark.protobuf.AddressBooks.Person.Phone other) {
          if (other == co.za.ravi.spark.protobuf.AddressBooks.Person.Phone.getDefaultInstance()) return this;
          if (other.hasPhoneNumber()) {
            bitField0_ |= 0x00000001;
            phoneNumber_ = other.phoneNumber_;
            onChanged();
          }
          if (other.hasType()) {
            setType(other.getType());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasPhoneNumber()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          co.za.ravi.spark.protobuf.AddressBooks.Person.Phone parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (co.za.ravi.spark.protobuf.AddressBooks.Person.Phone) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required string phoneNumber = 1;
        private java.lang.Object phoneNumber_ = "";
        /**
         * <code>required string phoneNumber = 1;</code>
         */
        public boolean hasPhoneNumber() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string phoneNumber = 1;</code>
         */
        public java.lang.String getPhoneNumber() {
          java.lang.Object ref = phoneNumber_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            phoneNumber_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string phoneNumber = 1;</code>
         */
        public com.google.protobuf.ByteString
            getPhoneNumberBytes() {
          java.lang.Object ref = phoneNumber_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            phoneNumber_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string phoneNumber = 1;</code>
         */
        public Builder setPhoneNumber(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          phoneNumber_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string phoneNumber = 1;</code>
         */
        public Builder clearPhoneNumber() {
          bitField0_ = (bitField0_ & ~0x00000001);
          phoneNumber_ = getDefaultInstance().getPhoneNumber();
          onChanged();
          return this;
        }
        /**
         * <code>required string phoneNumber = 1;</code>
         */
        public Builder setPhoneNumberBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          phoneNumber_ = value;
          onChanged();
          return this;
        }

        // optional .protobufexample.Person.PhoneType type = 2 [default = MOBILE];
        private co.za.ravi.spark.protobuf.AddressBooks.Person.PhoneType type_ = co.za.ravi.spark.protobuf.AddressBooks.Person.PhoneType.MOBILE;
        /**
         * <code>optional .protobufexample.Person.PhoneType type = 2 [default = MOBILE];</code>
         */
        public boolean hasType() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional .protobufexample.Person.PhoneType type = 2 [default = MOBILE];</code>
         */
        public co.za.ravi.spark.protobuf.AddressBooks.Person.PhoneType getType() {
          return type_;
        }
        /**
         * <code>optional .protobufexample.Person.PhoneType type = 2 [default = MOBILE];</code>
         */
        public Builder setType(co.za.ravi.spark.protobuf.AddressBooks.Person.PhoneType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000002;
          type_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional .protobufexample.Person.PhoneType type = 2 [default = MOBILE];</code>
         */
        public Builder clearType() {
          bitField0_ = (bitField0_ & ~0x00000002);
          type_ = co.za.ravi.spark.protobuf.AddressBooks.Person.PhoneType.MOBILE;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:protobufexample.Person.Phone)
      }

      static {
        defaultInstance = new Phone(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:protobufexample.Person.Phone)
    }

    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 id = 2;
    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    /**
     * <code>required int32 id = 2;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 id = 2;</code>
     */
    public int getId() {
      return id_;
    }

    // required string email = 3;
    public static final int EMAIL_FIELD_NUMBER = 3;
    private java.lang.Object email_;
    /**
     * <code>required string email = 3;</code>
     */
    public boolean hasEmail() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string email = 3;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          email_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string email = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated .protobufexample.Person.Phone phone = 4;
    public static final int PHONE_FIELD_NUMBER = 4;
    private java.util.List<co.za.ravi.spark.protobuf.AddressBooks.Person.Phone> phone_;
    /**
     * <code>repeated .protobufexample.Person.Phone phone = 4;</code>
     */
    public java.util.List<co.za.ravi.spark.protobuf.AddressBooks.Person.Phone> getPhoneList() {
      return phone_;
    }
    /**
     * <code>repeated .protobufexample.Person.Phone phone = 4;</code>
     */
    public java.util.List<? extends co.za.ravi.spark.protobuf.AddressBooks.Person.PhoneOrBuilder> 
        getPhoneOrBuilderList() {
      return phone_;
    }
    /**
     * <code>repeated .protobufexample.Person.Phone phone = 4;</code>
     */
    public int getPhoneCount() {
      return phone_.size();
    }
    /**
     * <code>repeated .protobufexample.Person.Phone phone = 4;</code>
     */
    public co.za.ravi.spark.protobuf.AddressBooks.Person.Phone getPhone(int index) {
      return phone_.get(index);
    }
    /**
     * <code>repeated .protobufexample.Person.Phone phone = 4;</code>
     */
    public co.za.ravi.spark.protobuf.AddressBooks.Person.PhoneOrBuilder getPhoneOrBuilder(
        int index) {
      return phone_.get(index);
    }

    private void initFields() {
      name_ = "";
      id_ = 0;
      email_ = "";
      phone_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEmail()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getPhoneCount(); i++) {
        if (!getPhone(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getEmailBytes());
      }
      for (int i = 0; i < phone_.size(); i++) {
        output.writeMessage(4, phone_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getEmailBytes());
      }
      for (int i = 0; i < phone_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, phone_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static co.za.ravi.spark.protobuf.AddressBooks.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static co.za.ravi.spark.protobuf.AddressBooks.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static co.za.ravi.spark.protobuf.AddressBooks.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static co.za.ravi.spark.protobuf.AddressBooks.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static co.za.ravi.spark.protobuf.AddressBooks.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static co.za.ravi.spark.protobuf.AddressBooks.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static co.za.ravi.spark.protobuf.AddressBooks.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static co.za.ravi.spark.protobuf.AddressBooks.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static co.za.ravi.spark.protobuf.AddressBooks.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static co.za.ravi.spark.protobuf.AddressBooks.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(co.za.ravi.spark.protobuf.AddressBooks.Person prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobufexample.Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements co.za.ravi.spark.protobuf.AddressBooks.PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return co.za.ravi.spark.protobuf.AddressBooks.internal_static_protobufexample_Person_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return co.za.ravi.spark.protobuf.AddressBooks.internal_static_protobufexample_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                co.za.ravi.spark.protobuf.AddressBooks.Person.class, co.za.ravi.spark.protobuf.AddressBooks.Person.Builder.class);
      }

      // Construct using co.za.ravi.spark.protobuf.AddressBooks.Person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPhoneFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        email_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        if (phoneBuilder_ == null) {
          phone_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          phoneBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return co.za.ravi.spark.protobuf.AddressBooks.internal_static_protobufexample_Person_descriptor;
      }

      public co.za.ravi.spark.protobuf.AddressBooks.Person getDefaultInstanceForType() {
        return co.za.ravi.spark.protobuf.AddressBooks.Person.getDefaultInstance();
      }

      public co.za.ravi.spark.protobuf.AddressBooks.Person build() {
        co.za.ravi.spark.protobuf.AddressBooks.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public co.za.ravi.spark.protobuf.AddressBooks.Person buildPartial() {
        co.za.ravi.spark.protobuf.AddressBooks.Person result = new co.za.ravi.spark.protobuf.AddressBooks.Person(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.email_ = email_;
        if (phoneBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            phone_ = java.util.Collections.unmodifiableList(phone_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.phone_ = phone_;
        } else {
          result.phone_ = phoneBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof co.za.ravi.spark.protobuf.AddressBooks.Person) {
          return mergeFrom((co.za.ravi.spark.protobuf.AddressBooks.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(co.za.ravi.spark.protobuf.AddressBooks.Person other) {
        if (other == co.za.ravi.spark.protobuf.AddressBooks.Person.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasEmail()) {
          bitField0_ |= 0x00000004;
          email_ = other.email_;
          onChanged();
        }
        if (phoneBuilder_ == null) {
          if (!other.phone_.isEmpty()) {
            if (phone_.isEmpty()) {
              phone_ = other.phone_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensurePhoneIsMutable();
              phone_.addAll(other.phone_);
            }
            onChanged();
          }
        } else {
          if (!other.phone_.isEmpty()) {
            if (phoneBuilder_.isEmpty()) {
              phoneBuilder_.dispose();
              phoneBuilder_ = null;
              phone_ = other.phone_;
              bitField0_ = (bitField0_ & ~0x00000008);
              phoneBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPhoneFieldBuilder() : null;
            } else {
              phoneBuilder_.addAllMessages(other.phone_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!hasId()) {
          
          return false;
        }
        if (!hasEmail()) {
          
          return false;
        }
        for (int i = 0; i < getPhoneCount(); i++) {
          if (!getPhone(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        co.za.ravi.spark.protobuf.AddressBooks.Person parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (co.za.ravi.spark.protobuf.AddressBooks.Person) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string name = 1;
      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      // required int32 id = 2;
      private int id_ ;
      /**
       * <code>required int32 id = 2;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 id = 2;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 2;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 2;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0;
        onChanged();
        return this;
      }

      // required string email = 3;
      private java.lang.Object email_ = "";
      /**
       * <code>required string email = 3;</code>
       */
      public boolean hasEmail() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string email = 3;</code>
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string email = 3;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string email = 3;</code>
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string email = 3;</code>
       */
      public Builder clearEmail() {
        bitField0_ = (bitField0_ & ~0x00000004);
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>required string email = 3;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        email_ = value;
        onChanged();
        return this;
      }

      // repeated .protobufexample.Person.Phone phone = 4;
      private java.util.List<co.za.ravi.spark.protobuf.AddressBooks.Person.Phone> phone_ =
        java.util.Collections.emptyList();
      private void ensurePhoneIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          phone_ = new java.util.ArrayList<co.za.ravi.spark.protobuf.AddressBooks.Person.Phone>(phone_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          co.za.ravi.spark.protobuf.AddressBooks.Person.Phone, co.za.ravi.spark.protobuf.AddressBooks.Person.Phone.Builder, co.za.ravi.spark.protobuf.AddressBooks.Person.PhoneOrBuilder> phoneBuilder_;

      /**
       * <code>repeated .protobufexample.Person.Phone phone = 4;</code>
       */
      public java.util.List<co.za.ravi.spark.protobuf.AddressBooks.Person.Phone> getPhoneList() {
        if (phoneBuilder_ == null) {
          return java.util.Collections.unmodifiableList(phone_);
        } else {
          return phoneBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protobufexample.Person.Phone phone = 4;</code>
       */
      public int getPhoneCount() {
        if (phoneBuilder_ == null) {
          return phone_.size();
        } else {
          return phoneBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protobufexample.Person.Phone phone = 4;</code>
       */
      public co.za.ravi.spark.protobuf.AddressBooks.Person.Phone getPhone(int index) {
        if (phoneBuilder_ == null) {
          return phone_.get(index);
        } else {
          return phoneBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protobufexample.Person.Phone phone = 4;</code>
       */
      public Builder setPhone(
          int index, co.za.ravi.spark.protobuf.AddressBooks.Person.Phone value) {
        if (phoneBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhoneIsMutable();
          phone_.set(index, value);
          onChanged();
        } else {
          phoneBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobufexample.Person.Phone phone = 4;</code>
       */
      public Builder setPhone(
          int index, co.za.ravi.spark.protobuf.AddressBooks.Person.Phone.Builder builderForValue) {
        if (phoneBuilder_ == null) {
          ensurePhoneIsMutable();
          phone_.set(index, builderForValue.build());
          onChanged();
        } else {
          phoneBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobufexample.Person.Phone phone = 4;</code>
       */
      public Builder addPhone(co.za.ravi.spark.protobuf.AddressBooks.Person.Phone value) {
        if (phoneBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhoneIsMutable();
          phone_.add(value);
          onChanged();
        } else {
          phoneBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protobufexample.Person.Phone phone = 4;</code>
       */
      public Builder addPhone(
          int index, co.za.ravi.spark.protobuf.AddressBooks.Person.Phone value) {
        if (phoneBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhoneIsMutable();
          phone_.add(index, value);
          onChanged();
        } else {
          phoneBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobufexample.Person.Phone phone = 4;</code>
       */
      public Builder addPhone(
          co.za.ravi.spark.protobuf.AddressBooks.Person.Phone.Builder builderForValue) {
        if (phoneBuilder_ == null) {
          ensurePhoneIsMutable();
          phone_.add(builderForValue.build());
          onChanged();
        } else {
          phoneBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobufexample.Person.Phone phone = 4;</code>
       */
      public Builder addPhone(
          int index, co.za.ravi.spark.protobuf.AddressBooks.Person.Phone.Builder builderForValue) {
        if (phoneBuilder_ == null) {
          ensurePhoneIsMutable();
          phone_.add(index, builderForValue.build());
          onChanged();
        } else {
          phoneBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobufexample.Person.Phone phone = 4;</code>
       */
      public Builder addAllPhone(
          java.lang.Iterable<? extends co.za.ravi.spark.protobuf.AddressBooks.Person.Phone> values) {
        if (phoneBuilder_ == null) {
          ensurePhoneIsMutable();
          super.addAll(values, phone_);
          onChanged();
        } else {
          phoneBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protobufexample.Person.Phone phone = 4;</code>
       */
      public Builder clearPhone() {
        if (phoneBuilder_ == null) {
          phone_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          phoneBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protobufexample.Person.Phone phone = 4;</code>
       */
      public Builder removePhone(int index) {
        if (phoneBuilder_ == null) {
          ensurePhoneIsMutable();
          phone_.remove(index);
          onChanged();
        } else {
          phoneBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protobufexample.Person.Phone phone = 4;</code>
       */
      public co.za.ravi.spark.protobuf.AddressBooks.Person.Phone.Builder getPhoneBuilder(
          int index) {
        return getPhoneFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protobufexample.Person.Phone phone = 4;</code>
       */
      public co.za.ravi.spark.protobuf.AddressBooks.Person.PhoneOrBuilder getPhoneOrBuilder(
          int index) {
        if (phoneBuilder_ == null) {
          return phone_.get(index);  } else {
          return phoneBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protobufexample.Person.Phone phone = 4;</code>
       */
      public java.util.List<? extends co.za.ravi.spark.protobuf.AddressBooks.Person.PhoneOrBuilder> 
           getPhoneOrBuilderList() {
        if (phoneBuilder_ != null) {
          return phoneBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(phone_);
        }
      }
      /**
       * <code>repeated .protobufexample.Person.Phone phone = 4;</code>
       */
      public co.za.ravi.spark.protobuf.AddressBooks.Person.Phone.Builder addPhoneBuilder() {
        return getPhoneFieldBuilder().addBuilder(
            co.za.ravi.spark.protobuf.AddressBooks.Person.Phone.getDefaultInstance());
      }
      /**
       * <code>repeated .protobufexample.Person.Phone phone = 4;</code>
       */
      public co.za.ravi.spark.protobuf.AddressBooks.Person.Phone.Builder addPhoneBuilder(
          int index) {
        return getPhoneFieldBuilder().addBuilder(
            index, co.za.ravi.spark.protobuf.AddressBooks.Person.Phone.getDefaultInstance());
      }
      /**
       * <code>repeated .protobufexample.Person.Phone phone = 4;</code>
       */
      public java.util.List<co.za.ravi.spark.protobuf.AddressBooks.Person.Phone.Builder> 
           getPhoneBuilderList() {
        return getPhoneFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          co.za.ravi.spark.protobuf.AddressBooks.Person.Phone, co.za.ravi.spark.protobuf.AddressBooks.Person.Phone.Builder, co.za.ravi.spark.protobuf.AddressBooks.Person.PhoneOrBuilder> 
          getPhoneFieldBuilder() {
        if (phoneBuilder_ == null) {
          phoneBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              co.za.ravi.spark.protobuf.AddressBooks.Person.Phone, co.za.ravi.spark.protobuf.AddressBooks.Person.Phone.Builder, co.za.ravi.spark.protobuf.AddressBooks.Person.PhoneOrBuilder>(
                  phone_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          phone_ = null;
        }
        return phoneBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:protobufexample.Person)
    }

    static {
      defaultInstance = new Person(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobufexample.Person)
  }

  public interface AddressBookOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .protobufexample.Person person = 1;
    /**
     * <code>repeated .protobufexample.Person person = 1;</code>
     */
    java.util.List<co.za.ravi.spark.protobuf.AddressBooks.Person> 
        getPersonList();
    /**
     * <code>repeated .protobufexample.Person person = 1;</code>
     */
    co.za.ravi.spark.protobuf.AddressBooks.Person getPerson(int index);
    /**
     * <code>repeated .protobufexample.Person person = 1;</code>
     */
    int getPersonCount();
    /**
     * <code>repeated .protobufexample.Person person = 1;</code>
     */
    java.util.List<? extends co.za.ravi.spark.protobuf.AddressBooks.PersonOrBuilder> 
        getPersonOrBuilderList();
    /**
     * <code>repeated .protobufexample.Person person = 1;</code>
     */
    co.za.ravi.spark.protobuf.AddressBooks.PersonOrBuilder getPersonOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code protobufexample.AddressBook}
   */
  public static final class AddressBook extends
      com.google.protobuf.GeneratedMessage
      implements AddressBookOrBuilder {
    // Use AddressBook.newBuilder() to construct.
    private AddressBook(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AddressBook(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AddressBook defaultInstance;
    public static AddressBook getDefaultInstance() {
      return defaultInstance;
    }

    public AddressBook getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AddressBook(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                person_ = new java.util.ArrayList<co.za.ravi.spark.protobuf.AddressBooks.Person>();
                mutable_bitField0_ |= 0x00000001;
              }
              person_.add(input.readMessage(co.za.ravi.spark.protobuf.AddressBooks.Person.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          person_ = java.util.Collections.unmodifiableList(person_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return co.za.ravi.spark.protobuf.AddressBooks.internal_static_protobufexample_AddressBook_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return co.za.ravi.spark.protobuf.AddressBooks.internal_static_protobufexample_AddressBook_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              co.za.ravi.spark.protobuf.AddressBooks.AddressBook.class, co.za.ravi.spark.protobuf.AddressBooks.AddressBook.Builder.class);
    }

    public static com.google.protobuf.Parser<AddressBook> PARSER =
        new com.google.protobuf.AbstractParser<AddressBook>() {
      public AddressBook parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AddressBook(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AddressBook> getParserForType() {
      return PARSER;
    }

    // repeated .protobufexample.Person person = 1;
    public static final int PERSON_FIELD_NUMBER = 1;
    private java.util.List<co.za.ravi.spark.protobuf.AddressBooks.Person> person_;
    /**
     * <code>repeated .protobufexample.Person person = 1;</code>
     */
    public java.util.List<co.za.ravi.spark.protobuf.AddressBooks.Person> getPersonList() {
      return person_;
    }
    /**
     * <code>repeated .protobufexample.Person person = 1;</code>
     */
    public java.util.List<? extends co.za.ravi.spark.protobuf.AddressBooks.PersonOrBuilder> 
        getPersonOrBuilderList() {
      return person_;
    }
    /**
     * <code>repeated .protobufexample.Person person = 1;</code>
     */
    public int getPersonCount() {
      return person_.size();
    }
    /**
     * <code>repeated .protobufexample.Person person = 1;</code>
     */
    public co.za.ravi.spark.protobuf.AddressBooks.Person getPerson(int index) {
      return person_.get(index);
    }
    /**
     * <code>repeated .protobufexample.Person person = 1;</code>
     */
    public co.za.ravi.spark.protobuf.AddressBooks.PersonOrBuilder getPersonOrBuilder(
        int index) {
      return person_.get(index);
    }

    private void initFields() {
      person_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getPersonCount(); i++) {
        if (!getPerson(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < person_.size(); i++) {
        output.writeMessage(1, person_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < person_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, person_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static co.za.ravi.spark.protobuf.AddressBooks.AddressBook parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static co.za.ravi.spark.protobuf.AddressBooks.AddressBook parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static co.za.ravi.spark.protobuf.AddressBooks.AddressBook parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static co.za.ravi.spark.protobuf.AddressBooks.AddressBook parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static co.za.ravi.spark.protobuf.AddressBooks.AddressBook parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static co.za.ravi.spark.protobuf.AddressBooks.AddressBook parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static co.za.ravi.spark.protobuf.AddressBooks.AddressBook parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static co.za.ravi.spark.protobuf.AddressBooks.AddressBook parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static co.za.ravi.spark.protobuf.AddressBooks.AddressBook parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static co.za.ravi.spark.protobuf.AddressBooks.AddressBook parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(co.za.ravi.spark.protobuf.AddressBooks.AddressBook prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobufexample.AddressBook}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements co.za.ravi.spark.protobuf.AddressBooks.AddressBookOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return co.za.ravi.spark.protobuf.AddressBooks.internal_static_protobufexample_AddressBook_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return co.za.ravi.spark.protobuf.AddressBooks.internal_static_protobufexample_AddressBook_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                co.za.ravi.spark.protobuf.AddressBooks.AddressBook.class, co.za.ravi.spark.protobuf.AddressBooks.AddressBook.Builder.class);
      }

      // Construct using co.za.ravi.spark.protobuf.AddressBooks.AddressBook.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPersonFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (personBuilder_ == null) {
          person_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          personBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return co.za.ravi.spark.protobuf.AddressBooks.internal_static_protobufexample_AddressBook_descriptor;
      }

      public co.za.ravi.spark.protobuf.AddressBooks.AddressBook getDefaultInstanceForType() {
        return co.za.ravi.spark.protobuf.AddressBooks.AddressBook.getDefaultInstance();
      }

      public co.za.ravi.spark.protobuf.AddressBooks.AddressBook build() {
        co.za.ravi.spark.protobuf.AddressBooks.AddressBook result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public co.za.ravi.spark.protobuf.AddressBooks.AddressBook buildPartial() {
        co.za.ravi.spark.protobuf.AddressBooks.AddressBook result = new co.za.ravi.spark.protobuf.AddressBooks.AddressBook(this);
        int from_bitField0_ = bitField0_;
        if (personBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            person_ = java.util.Collections.unmodifiableList(person_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.person_ = person_;
        } else {
          result.person_ = personBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof co.za.ravi.spark.protobuf.AddressBooks.AddressBook) {
          return mergeFrom((co.za.ravi.spark.protobuf.AddressBooks.AddressBook)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(co.za.ravi.spark.protobuf.AddressBooks.AddressBook other) {
        if (other == co.za.ravi.spark.protobuf.AddressBooks.AddressBook.getDefaultInstance()) return this;
        if (personBuilder_ == null) {
          if (!other.person_.isEmpty()) {
            if (person_.isEmpty()) {
              person_ = other.person_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePersonIsMutable();
              person_.addAll(other.person_);
            }
            onChanged();
          }
        } else {
          if (!other.person_.isEmpty()) {
            if (personBuilder_.isEmpty()) {
              personBuilder_.dispose();
              personBuilder_ = null;
              person_ = other.person_;
              bitField0_ = (bitField0_ & ~0x00000001);
              personBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPersonFieldBuilder() : null;
            } else {
              personBuilder_.addAllMessages(other.person_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getPersonCount(); i++) {
          if (!getPerson(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        co.za.ravi.spark.protobuf.AddressBooks.AddressBook parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (co.za.ravi.spark.protobuf.AddressBooks.AddressBook) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .protobufexample.Person person = 1;
      private java.util.List<co.za.ravi.spark.protobuf.AddressBooks.Person> person_ =
        java.util.Collections.emptyList();
      private void ensurePersonIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          person_ = new java.util.ArrayList<co.za.ravi.spark.protobuf.AddressBooks.Person>(person_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          co.za.ravi.spark.protobuf.AddressBooks.Person, co.za.ravi.spark.protobuf.AddressBooks.Person.Builder, co.za.ravi.spark.protobuf.AddressBooks.PersonOrBuilder> personBuilder_;

      /**
       * <code>repeated .protobufexample.Person person = 1;</code>
       */
      public java.util.List<co.za.ravi.spark.protobuf.AddressBooks.Person> getPersonList() {
        if (personBuilder_ == null) {
          return java.util.Collections.unmodifiableList(person_);
        } else {
          return personBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protobufexample.Person person = 1;</code>
       */
      public int getPersonCount() {
        if (personBuilder_ == null) {
          return person_.size();
        } else {
          return personBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protobufexample.Person person = 1;</code>
       */
      public co.za.ravi.spark.protobuf.AddressBooks.Person getPerson(int index) {
        if (personBuilder_ == null) {
          return person_.get(index);
        } else {
          return personBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protobufexample.Person person = 1;</code>
       */
      public Builder setPerson(
          int index, co.za.ravi.spark.protobuf.AddressBooks.Person value) {
        if (personBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePersonIsMutable();
          person_.set(index, value);
          onChanged();
        } else {
          personBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobufexample.Person person = 1;</code>
       */
      public Builder setPerson(
          int index, co.za.ravi.spark.protobuf.AddressBooks.Person.Builder builderForValue) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          person_.set(index, builderForValue.build());
          onChanged();
        } else {
          personBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobufexample.Person person = 1;</code>
       */
      public Builder addPerson(co.za.ravi.spark.protobuf.AddressBooks.Person value) {
        if (personBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePersonIsMutable();
          person_.add(value);
          onChanged();
        } else {
          personBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protobufexample.Person person = 1;</code>
       */
      public Builder addPerson(
          int index, co.za.ravi.spark.protobuf.AddressBooks.Person value) {
        if (personBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePersonIsMutable();
          person_.add(index, value);
          onChanged();
        } else {
          personBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobufexample.Person person = 1;</code>
       */
      public Builder addPerson(
          co.za.ravi.spark.protobuf.AddressBooks.Person.Builder builderForValue) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          person_.add(builderForValue.build());
          onChanged();
        } else {
          personBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobufexample.Person person = 1;</code>
       */
      public Builder addPerson(
          int index, co.za.ravi.spark.protobuf.AddressBooks.Person.Builder builderForValue) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          person_.add(index, builderForValue.build());
          onChanged();
        } else {
          personBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobufexample.Person person = 1;</code>
       */
      public Builder addAllPerson(
          java.lang.Iterable<? extends co.za.ravi.spark.protobuf.AddressBooks.Person> values) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          super.addAll(values, person_);
          onChanged();
        } else {
          personBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protobufexample.Person person = 1;</code>
       */
      public Builder clearPerson() {
        if (personBuilder_ == null) {
          person_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          personBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protobufexample.Person person = 1;</code>
       */
      public Builder removePerson(int index) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          person_.remove(index);
          onChanged();
        } else {
          personBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protobufexample.Person person = 1;</code>
       */
      public co.za.ravi.spark.protobuf.AddressBooks.Person.Builder getPersonBuilder(
          int index) {
        return getPersonFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protobufexample.Person person = 1;</code>
       */
      public co.za.ravi.spark.protobuf.AddressBooks.PersonOrBuilder getPersonOrBuilder(
          int index) {
        if (personBuilder_ == null) {
          return person_.get(index);  } else {
          return personBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protobufexample.Person person = 1;</code>
       */
      public java.util.List<? extends co.za.ravi.spark.protobuf.AddressBooks.PersonOrBuilder> 
           getPersonOrBuilderList() {
        if (personBuilder_ != null) {
          return personBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(person_);
        }
      }
      /**
       * <code>repeated .protobufexample.Person person = 1;</code>
       */
      public co.za.ravi.spark.protobuf.AddressBooks.Person.Builder addPersonBuilder() {
        return getPersonFieldBuilder().addBuilder(
            co.za.ravi.spark.protobuf.AddressBooks.Person.getDefaultInstance());
      }
      /**
       * <code>repeated .protobufexample.Person person = 1;</code>
       */
      public co.za.ravi.spark.protobuf.AddressBooks.Person.Builder addPersonBuilder(
          int index) {
        return getPersonFieldBuilder().addBuilder(
            index, co.za.ravi.spark.protobuf.AddressBooks.Person.getDefaultInstance());
      }
      /**
       * <code>repeated .protobufexample.Person person = 1;</code>
       */
      public java.util.List<co.za.ravi.spark.protobuf.AddressBooks.Person.Builder> 
           getPersonBuilderList() {
        return getPersonFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          co.za.ravi.spark.protobuf.AddressBooks.Person, co.za.ravi.spark.protobuf.AddressBooks.Person.Builder, co.za.ravi.spark.protobuf.AddressBooks.PersonOrBuilder> 
          getPersonFieldBuilder() {
        if (personBuilder_ == null) {
          personBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              co.za.ravi.spark.protobuf.AddressBooks.Person, co.za.ravi.spark.protobuf.AddressBooks.Person.Builder, co.za.ravi.spark.protobuf.AddressBooks.PersonOrBuilder>(
                  person_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          person_ = null;
        }
        return personBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:protobufexample.AddressBook)
    }

    static {
      defaultInstance = new AddressBook(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobufexample.AddressBook)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobufexample_Person_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobufexample_Person_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobufexample_Person_Phone_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobufexample_Person_Phone_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobufexample_AddressBook_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobufexample_AddressBook_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021addressbook.proto\022\017protobufexample\"\343\001\n" +
      "\006Person\022\014\n\004name\030\001 \002(\t\022\n\n\002id\030\002 \002(\005\022\r\n\005ema" +
      "il\030\003 \002(\t\022,\n\005phone\030\004 \003(\0132\035.protobufexampl" +
      "e.Person.Phone\032U\n\005Phone\022\023\n\013phoneNumber\030\001" +
      " \002(\t\0227\n\004type\030\002 \001(\0162!.protobufexample.Per" +
      "son.PhoneType:\006MOBILE\"+\n\tPhoneType\022\010\n\004HO" +
      "ME\020\000\022\010\n\004WORK\020\001\022\n\n\006MOBILE\020\002\"6\n\013AddressBoo" +
      "k\022\'\n\006person\030\001 \003(\0132\027.protobufexample.Pers" +
      "onB)\n\031co.za.ravi.spark.protobufB\014Address" +
      "Books"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protobufexample_Person_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protobufexample_Person_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobufexample_Person_descriptor,
              new java.lang.String[] { "Name", "Id", "Email", "Phone", });
          internal_static_protobufexample_Person_Phone_descriptor =
            internal_static_protobufexample_Person_descriptor.getNestedTypes().get(0);
          internal_static_protobufexample_Person_Phone_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobufexample_Person_Phone_descriptor,
              new java.lang.String[] { "PhoneNumber", "Type", });
          internal_static_protobufexample_AddressBook_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_protobufexample_AddressBook_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobufexample_AddressBook_descriptor,
              new java.lang.String[] { "Person", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
